[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[redirects]]
  from="/api/functions/*"
  to="/.netlify/functions/:splat"
  status=200
  force=true

[[plugins]]
  package = "@netlify/plugin-nextjs"